/**
 * Build the DSH web client bundle (`lib/client.js`).
 *
 * Matches the official DSH client-module format:
 *   window.__ModuleLoader__.load({ id, factory: (require) => { ... } })
 *
 * - Host-provided deps (react, react-dom, @deepseek-ai/*) stay external and
 *   resolve through the factory's `require()`.
 * - Everything else (@xyflow/react, zustand, our own modules) is bundled inline.
 * - Plugin CSS is inlined and injected as a <style> element on module load.
 */
import { build } from 'esbuild'
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const root = dirname(dirname(fileURLToPath(import.meta.url)))
const PKG = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'))

const result = await build({
  entryPoints: [join(root, 'src/ui.ts')],
  bundle: true,
  format: 'cjs',
  platform: 'browser',
  target: ['es2022'],
  jsx: 'automatic',
  minify: true,
  write: false,
  external: [
    'react',
    'react-dom',
    'react-dom/*',
    'react/jsx-runtime',
    '@deepseek-ai/*',
  ],
  loader: {
    '.css': 'text',
  },
  define: {
    'process.env.NODE_ENV': '"production"',
  },
  logLevel: 'info',
})

const code = result.outputFiles[0].text
const css = readFileSync(join(root, 'src/components/canvas.css'), 'utf8')

const banner = `/* Generated by build-client.mjs — do not edit. */
window.__ModuleLoader__.load({
\tid: ${JSON.stringify(PKG.name)},
\tfactory: (require) => {
\t\tvar module = { exports: {} };
\t\tvar exports = module.exports;
`

const cssInject = `\n\t\ttry {
\t\t\tvar style = document.createElement('style');
\t\t\tstyle.setAttribute('data-dsh-plugin', ${JSON.stringify(PKG.name)});
\t\t\tstyle.textContent = ${JSON.stringify(css)};
\t\t\tdocument.head.appendChild(style);
\t\t} catch (e) { /* style injection is best-effort */ }
`

const footer = `\n\t\treturn module.exports;
\t}
});
`

writeFileSync(join(root, 'lib/client.js'), banner + cssInject + code + footer)
console.log(`wrote lib/client.js (${(banner + cssInject + code + footer).length} bytes)`)
